### ISSUE TITLE
Compiler does not recognize 'size_t' type (MacOS version)

### ISSUE THREAD

**Issue by driftwood74** [MartianGirl/SpecIde#1]
The MacOS version delivers a list of errors at the "make" step. All errors refer to size_t type:

/Users/mhajsaleh/GitHub/SpecIde/source/src/ULA.h:24:16: error: unknown type name
      'size_t'

**Comment by MartianGirl** [comment]
#include <cstddef>
en cada fichero afectado


On Jul 22, 2017 21:56, "Otis B. Driftwood" <notifications@github.com> wrote:

The MacOS version delivers a list of errors at the "make" step. All errors
refer to size_t type:

/Users/mhajsaleh/GitHub/SpecIde/source/src/ULA.h:24:16: error: unknown type
name
'size_t'

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/MartianGirl/SpecIde/issues/1>, or mute the thread

**Comment by driftwood74** [comment]
Done. It work just by adding the #include to ULA.h :-)
