### ISSUE TITLE
+2A/+3 Floating bus

### ISSUE THREAD

**Issue by DrWhat** [MartianGirl/SpecIde#2]
The two tests that I developed specifically to help emulator authors are these:

1. [Universal Floating Bust Test](http://sky.relative-path.com/zx/files/Plus_2A_test.zip)
—When you run it, there should be two yellow horizontal lines in the black border around the “ground level.” The lines should _never_ appear above the ground.
—Press a key, and the top of the screen will fill with a pattern. Again, the yellow lines should never appear anywhere but at the ground level.
—Now hold a key down. A single yellow line should jump around the ground area but should never appear anywhere else, however briefly.

2. [Woody’s Special](http://sky.relative-path.com/zx/files/Woody_s_special.zip)
Unlike the universal test above, this one is design with a +2A/+3 in mind.
—When you run it, there should be two yellow horizontal lines in the black border around the “ground level.” The lines should _never_ appear above the ground.
—Press a key, and the top of the screen will fill with a pattern. Several additional yellow lines should flicker in the top part of the border, and a few more immediately underneath the two solid ones below the ground level.
Use this video as a reference (it’s shot at 50 fps, so you can be at least frame-accurate):
[Woody’s Special: Video of a Real Spectrum +2A](http://sky.relative-path.com/zx/files/woody_vid_1.mp4)

Hope this helps!

**Comment by MartianGirl** [comment]
I've just noticed that the way I accept maskable interrupts in my Z80 implementation is wrong. Interrupt pin is sampled at the beginning of the last T-state of the last M-cycle of any instruction. I was checking the pin too often.

I'm going to try to fix this, and then rework the synchronization.

**Comment by DrWhat** [comment]
Yes, and the /BUSREQ must also be low. A new M cycle is generated, as well.

Not sure how these timings will affect the floating bus, but I eagerly await your next update!

**Comment by MartianGirl** [comment]
Fixed in 7e80b835e46ec836d7ea8aaf8ffaf6f8560132c2

**Comment by MartianGirl** [comment]
Fixed in 7e80b835e46ec836d7ea8aaf8ffaf6f8560132c2.

**Comment by DrWhat** [comment]
Excellent, and very, _very_ close. You’re just 4 T states late, though. ;)

**Comment by MartianGirl** [comment]
Hi :)

I already knew that, but think that I'm not using those tables for calculating the contention in 48/128K and neither in +2A. My implementation of contention is based in the actual Z80 signals. In 48K/128K I apply contention whenever a contended page is accessed, as long as MREQ is not active, or when IORQ is active and the port address is even. In the +2A I'm not applying any I/O contention, and I'm using MREQ low to decide when do I have to bring WAIT low. Most things work like this, like the Shock Megademo. However, the text scroller in SongInLines4 doesn't, neither in 128K nor in +2A. I'll have to disassemble that, and learn how the synchronization is being made, because I just figured it out and adjusted until the tests programs (prtiming.tap, woodys special, fbtest, fusetest, etc.) worked.

I'd have to see if there is any instruction where I am missing the WAIT state, or if my implementations of Z80 cycles are correct, but they seem mostly fine (I don't think that Shock would work at all if that wasn't). I'd need more +2A specific demos, just to test quite a lot more my timings... :)

**Comment by DrWhat** [comment]
Okay, how can I contact you privately? (Not that the source code is a big trade secret; I just don’t feel like sharing it here.)

The snow effect? No, I didn’t know you did it! I guess I was too busy enjoying the spring to think about snow. I did some snow tests as well (not very extensively), so I might run some test for you on a real Toast Rack at some point.

**Comment by MartianGirl** [comment]
I believe I have just fixed this, in commit 5e90a61958541a301977f6083063415ae8e3a7cb
