### ISSUE TITLE
Keys to load

### ISSUE THREAD

**Issue by maziac** [MartianGirl/SpecIde#7]
Hi,

what is the key combination on Mac to enter 
LOAD "" CODE

Especially what key combination is used for ".
I tried all key combinations with P but nothing seems to work.

**Comment by MartianGirl** [comment]
Hi,

It should be Ctrl + P

I've mapped both Ctrl keys to Symbol Shift:

        case Keyboard::LControl:    // Symbol Shift
        case Keyboard::RControl:
            keyboardMask[0] = 0xFD; break;

Also, the single quote key (') is mapped to this same combination.

        case Keyboard::Quote:   // Symbol Shift + P
            keyboardMask[0] = 0xFD;
            keyboardMask[2] = 0xFE; break;

Also, for CODE it would be Shift + Control (or simply Alt) for Extend Mode, then press the i key.

Maybe check if it works with Cmd instead of Ctrl. I actually don't have a Mac to try it right now, but I've definitely tested it in Mac.

**Comment by maziac** [comment]
Thanks. It turned out that my keyboard mapping was wrong.
Now its' working.

**Comment by MartianGirl** [comment]
Awesome :)

Enjoy SpecIde! :)

**Comment by maziac** [comment]
I do :-)
